/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_never_nikkaandroid_base_JniHello */

#ifndef _Included_com_never_nikkaandroid_base_JniHello
#define _Included_com_never_nikkaandroid_base_JniHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_never_nikkaandroid_base_JniHello
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_never_nikkaandroid_base_JniHello_SayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_never_nikkaandroid_base_JniHello
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_never_nikkaandroid_base_JniHello_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_never_nikkaandroid_base_JniHello
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_never_nikkaandroid_base_JniHello_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_never_nikkaandroid_base_JniHello
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_never_nikkaandroid_base_JniHello_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_never_nikkaandroid_base_JniHello
 * Method:    serialWithUserID
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_never_nikkaandroid_base_JniHello_serialWithUserID
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
